import React from 'react';
import './PageStyles.css';
import mainImage from '../assets/main.jpg'; // adjust path based on the file location

export default function Home() {
    return (
        <div className="page home-page">
            <section className="hero">
                <div className="hero-text">
                    <h1>Welcome to DishMuse 🍽️</h1>
                    <p>Enter ingredients and discover magical recipes generated by AI.</p>
                    <a href="/create" className="cta-button">Start Creating</a>
                </div>
                <img
                    src={mainImage}
                    alt="Delicious food"
                    className="hero-image"
                />

            </section>

            <section className="features">
                <h2>✨ Why DishMuse?</h2>
                <div className="feature-grid">
                    <div className="feature">
                        <img src="https://cdn-icons-png.flaticon.com/512/3480/3480428.png" alt="AI" />
                        <h3>AI-Powered</h3>
                        <p>Smart suggestions based on your available ingredients.</p>
                    </div>
                    <div className="feature">
                        <img src="https://cdn-icons-png.flaticon.com/512/135/135620.png" alt="Quick" />
                        <h3>Fast & Easy</h3>
                        <p>Get instant recipes without long cooking videos or boring ads.</p>
                    </div>
                    <div className="feature">
                        <img src="https://cdn-icons-png.flaticon.com/512/2921/2921822.png" alt="Healthy" />
                        <h3>Healthy Choices</h3>
                        <p>We promote recipes that balance taste and nutrition.</p>
                    </div>
                </div>
            </section>
        </div>
    );
}
